# .yamllint.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

extends: default

# to be compatible with prettier
rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  document-start: disable
