- name: Install pipx with DNF
  ansible.builtin.package:
    name: pipx
    state: present
- name: Install latest pipx with pipx
  community.general.pipx:
    name: pipx
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
