# on Ubuntu assumes that the apt cache was updated previously, e.g. in python311
- name: Install pipx with the system package manager
  ansible.builtin.package:
    name: pipx
    state: present
  become: true
- name: Install the latest pipx with pipx
  community.general.pipx:
    name: pipx
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
  become: true
