- name: Identify the Linux distribution
  ansible.builtin.setup: { gather_subset: [distribution] }
# assumes that the apt cache was updated previously, e.g. in python311
- name: On Ubuntu install the python3-venv package
  ansible.builtin.package:
    name: python3-venv
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'
- name: Download pipx zipapp to /usr/local/bin/
  ansible.builtin.get_url:
    url: https://github.com/pypa/pipx/releases/download/1.4.3/pipx.pyz
    dest: /usr/local/bin/pipx
    mode: "0755"
    owner: root
    group: root
  become: true
