- name: Install python launcher
  ansible.builtin.package:
    name: python-launcher
    state: present
  become: true
- name: Install latest nox with pipx
  community.general.pipx:
    name: nox
    executable: /usr/local/bin/pipx
    python: "3.11"
  environment: "{{ nox_environment }}"
  become: true
