- name: Install latest nox with pipx
  community.general.pipx:
    name: nox
    executable: /usr/local/bin/pipx
    python: |-
      {{ '/usr/bin/python3.11' if ansible_distribution == 'Ubuntu' else omit }}
  environment: "{{ nox_environment }}"
  become: true
