- name: Install latest nox with pipx
  community.general.pipx:
    name: nox
    executable: /usr/local/bin/pipx
    python: "3.11"
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
  become: true
