# .github/workflows/lxd.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: canonical/setup-lxd@v0.1.1
      - run: . .README.md-files/install-pwd.sh
      - run: . .README.md-files/ubuntu-python311.sh
      - run: lxc exec c1 -- python3.11 --version
      - run: lxc delete --force c1
      - run: . .README.md-files/ubuntu-python312.sh
      - run: lxc exec c1 -- python3.12 --version
      - run: lxc delete --force c1
      - run: . .README.md-files/ubuntu-pipx.sh
      - run: lxc exec c1 -- pipx --version
      - run: lxc delete --force c1
      - run: . .README.md-files/ubuntu-nox.sh
      - run: lxc exec c1 -- nox --version
      - run: >-
          lxc exec c1
          --env PIPX_BIN_DIR=/usr/local/bin --env PIPX_HOME=/opt/pipx
          -- pipx list
      - run: lxc delete --force c1
