# .github/workflows/lxd.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: canonical/setup-lxd@v0.1.1
      - run: . .README.md-files/install-pwd.sh
      - run: . .README.md-files/ubuntu-pyhton311.sh
      - run: lxc delete --force c1
      - run: . .README.md-files/ubuntu-pipx.sh
      - run: lxc delete --force c1
      - run: . .README.md-files/ubuntu-nox.sh
      - run: lxc delete --force c1
