# .github/workflows/static-analysis.yaml
# Copyright 2023 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v2
      - run: git ls-files '*.yaml' '*.yml' | xargs npm exec prettier -- --check
      - run: >-
          git ls-files '*.md'
          | xargs npm exec prettier -- --check --prose-wrap always
